import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter/services.dart';
import '../../../widgets/custom_button.dart';
import '../../../widgets/login/login_colors.dart';
import '../../../services/auth_service.dart';
import '../../../app/navigation/route_names.dart';

/// Two-Factor Auth Setup Screen - İki faktörlü doğrulama kurulum ekranı
class TwoFactorSetupScreen extends StatefulWidget {
  const TwoFactorSetupScreen({super.key});

  @override
  State<TwoFactorSetupScreen> createState() => _TwoFactorSetupScreenState();
}

class _TwoFactorSetupScreenState extends State<TwoFactorSetupScreen> {
  final _authService = AuthService();
  bool _isLoading = false;
  String? _secretKey;
  String? _qrCodeUrl;
  List<String> _backupCodes = [];

  @override
  void initState() {
    super.initState();
    _generateSecret();
  }

  Future<void> _generateSecret() async {
    setState(() {
      _isLoading = true;
    });

    try {
      // TODO: Uncomment when backend is ready
      // final result = await _authService.generate2FASecret();
      // setState(() {
      //   _secretKey = result['secret'];
      //   _qrCodeUrl = result['qr_code_url'];
      //   _backupCodes = List<String>.from(result['backup_codes']);
      // });
      
      // Mock data for development
      await Future.delayed(const Duration(seconds: 1));
      
      setState(() {
        _secretKey = 'JBSWY3DPEHPK3PXP';
        _qrCodeUrl = null; // QR code would be generated by backend
        _backupCodes = [
          '1234-5678',
          '2345-6789',
          '3456-7890',
          '4567-8901',
          '5678-9012',
        ];
        _isLoading = false;
      });
    } catch (e) {
      if (!mounted) return;

      setState(() {
        _isLoading = false;
      });

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Hata: ${e.toString()}'),
          backgroundColor: LoginColors.orangeDark,
        ),
      );
    }
  }

  Future<void> _copySecret() async {
    if (_secretKey == null) return;
    
    await Clipboard.setData(ClipboardData(text: _secretKey!));
    
    if (!mounted) return;
    
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Gizli anahtar kopyalandı'),
        backgroundColor: Colors.green,
      ),
    );
  }

  Future<void> _copyBackupCodes() async {
    if (_backupCodes.isEmpty) return;
    
    final codesText = _backupCodes.join('\n');
    await Clipboard.setData(ClipboardData(text: codesText));
    
    if (!mounted) return;
    
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Yedek kodlar kopyalandı'),
        backgroundColor: Colors.green,
      ),
    );
  }

  void _continueToVerify() {
    context.push(AppRoutes.twoFactorVerify, extra: {
      'secret': _secretKey,
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: LoginColors.darkGray,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new, color: LoginColors.textPrimary),
          onPressed: () => context.pop(),
        ),
      ),
      body: SafeArea(
        child: _isLoading
            ? const Center(
                child: CircularProgressIndicator(
                  color: LoginColors.orangeBright,
                ),
              )
            : SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 24),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    const SizedBox(height: 40),
                    
                    // Icon
                    Center(
                      child: Container(
                        width: 80,
                        height: 80,
                        decoration: BoxDecoration(
                          gradient: LoginColors.orangeGradient,
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(
                          Icons.security,
                          size: 40,
                          color: Colors.white,
                        ),
                      ),
                    ),
                    const SizedBox(height: 32),
                    
                    // Başlık
                    const Text(
                      'İki Faktörlü Doğrulama',
                      style: TextStyle(
                        color: LoginColors.textPrimary,
                        fontSize: 28,
                        fontWeight: FontWeight.bold,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 16),
                    const Text(
                      'Hesabınızı ekstra güvenlik katmanı ile koruyun',
                      style: TextStyle(
                        color: LoginColors.textSecondary,
                        fontSize: 16,
                        height: 1.5,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 48),
                    
                    // QR Code placeholder
                    Container(
                      width: 200,
                      height: 200,
                      margin: const EdgeInsets.symmetric(horizontal: 50),
                      decoration: BoxDecoration(
                        color: LoginColors.mediumGray,
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(
                          color: LoginColors.lightGray,
                          width: 1,
                        ),
                      ),
                      child: _qrCodeUrl != null
                          ? Image.network(_qrCodeUrl!)
                          : Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(
                                  Icons.qr_code,
                                  size: 80,
                                  color: LoginColors.textSecondary,
                                ),
                                const SizedBox(height: 16),
                                Text(
                                  'QR Kod',
                                  style: TextStyle(
                                    color: LoginColors.textSecondary,
                                    fontSize: 14,
                                  ),
                                ),
                              ],
                            ),
                    ),
                    const SizedBox(height: 32),
                    
                    // Secret key
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: LoginColors.mediumGray,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(
                          color: LoginColors.lightGray,
                          width: 1,
                        ),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              const Icon(
                                Icons.key,
                                color: LoginColors.orangeBright,
                                size: 20,
                              ),
                              const SizedBox(width: 8),
                              const Text(
                                'Gizli Anahtar',
                                style: TextStyle(
                                  color: LoginColors.textPrimary,
                                  fontSize: 14,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                              const Spacer(),
                              IconButton(
                                icon: const Icon(
                                  Icons.copy,
                                  size: 20,
                                  color: LoginColors.orangeBright,
                                ),
                                onPressed: _copySecret,
                              ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          SelectableText(
                            _secretKey ?? '',
                            style: const TextStyle(
                              color: LoginColors.textPrimary,
                              fontSize: 16,
                              fontFamily: 'monospace',
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),
                    
                    // Instructions
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: LoginColors.orange.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(
                          color: LoginColors.orangeBright.withOpacity(0.3),
                          width: 1,
                        ),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              Icon(
                                Icons.info_outline,
                                color: LoginColors.orangeBright,
                                size: 20,
                              ),
                              const SizedBox(width: 8),
                              Text(
                                'Nasıl Kullanılır?',
                                style: TextStyle(
                                  color: LoginColors.orangeBright,
                                  fontSize: 14,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 12),
                          _buildInstruction('1. Google Authenticator veya benzeri bir uygulama indirin'),
                          _buildInstruction('2. QR kodu tarayın veya gizli anahtarı manuel girin'),
                          _buildInstruction('3. Uygulamadan gelen 6 haneli kodu doğrulayın'),
                        ],
                      ),
                    ),
                    const SizedBox(height: 32),
                    
                    // Backup codes
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: LoginColors.mediumGray,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(
                          color: LoginColors.lightGray,
                          width: 1,
                        ),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              const Icon(
                                Icons.backup,
                                color: LoginColors.orangeBright,
                                size: 20,
                              ),
                              const SizedBox(width: 8),
                              const Text(
                                'Yedek Kodlar',
                                style: TextStyle(
                                  color: LoginColors.textPrimary,
                                  fontSize: 14,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                              const Spacer(),
                              IconButton(
                                icon: const Icon(
                                  Icons.copy,
                                  size: 20,
                                  color: LoginColors.orangeBright,
                                ),
                                onPressed: _copyBackupCodes,
                              ),
                            ],
                          ),
                          const SizedBox(height: 12),
                          ..._backupCodes.map((code) => Padding(
                                padding: const EdgeInsets.only(bottom: 8),
                                child: SelectableText(
                                  code,
                                  style: const TextStyle(
                                    color: LoginColors.textPrimary,
                                    fontSize: 14,
                                    fontFamily: 'monospace',
                                  ),
                                ),
                              )),
                          const SizedBox(height: 8),
                          Text(
                            'Bu kodları güvenli bir yerde saklayın. Telefonunuzu kaybederseniz bu kodlarla giriş yapabilirsiniz.',
                            style: TextStyle(
                              color: LoginColors.textSecondary,
                              fontSize: 12,
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 32),
                    
                    // Continue button
                    CustomButton(
                      text: 'Devam Et ve Doğrula',
                      icon: Icons.arrow_forward,
                      onPressed: _continueToVerify,
                    ),
                    const SizedBox(height: 32),
                  ],
                ),
              ),
      ),
    );
  }

  Widget _buildInstruction(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '• ',
            style: TextStyle(
              color: LoginColors.orangeBright,
              fontSize: 16,
            ),
          ),
          Expanded(
            child: Text(
              text,
              style: const TextStyle(
                color: LoginColors.textPrimary,
                fontSize: 14,
                height: 1.4,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

